name: Run ktlint

on:
  pull_request:
    branches: [ "master" ]
  push:
    branches: [ "master" ]

jobs:
  ktlint:
    name: Run ktlint
    runs-on: ubuntu-latest

    steps:
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      
    - name: Checkout
      uses: actions/checkout@v3
      with:
        path: kr
        
    - run: |
        sudo chown -R root:root $GITHUB_WORKSPACE
        
    - name: Run ktlint
      uses: wing-tree/action-ktlint@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        reporter: github-pr-review
        custom_rule_path: "kr/krs3.jar"
        android: true
        fail_on_error: true
        level: warning
